read_quality_threshold: 28
read_trim_length_threshold: 150
maximum_overlap: 300
minimum_overlap: 20
amplicon_size:
  For1Rev2: 378
  For3Rev1: 318
  DRB3: 324
read_count_percent_threshold: 
  For1Rev2: 0.2
  For3Rev1: 0.2
  DRB3: 5
no_of_clusters: 1000
primers:
  For1Rev2: "fasta/Bovine.For1Rev2.primers.fa"
  For3Rev1: "fasta/Bovine.For3Rev1.primers.fa"
database:
  For1Rev2: "fasta/Bovine.MHCI.fasta"
  For3Rev1: "fasta/Bovine.MHCI.fasta"
samples:
  - 2372N0003
  - 2372N0004
  - 2372N0005
reads:
  2372N0003: "2372N0003_ATTACTCG-TATAGCCT_L001"
  2372N0004: "2372N0004_ATTACTCG-ATAGAGGC_L001"
  2372N0005: "2372N0005_ATTACTCG-CCTATCCT_L001"
